"""Generate a verified watchlist.yaml from the candidate universe.

The candidate list lives in ``scripts/candidates.yaml`` (data, hand-maintained); this
module is the logic (probe + emit). For each candidate we try its Yahoo tickers
(different exchange listings of the same ISIN) and keep the first that returns price
history, batching the probes so we make only a few requests per round. Candidates whose
tickers all fail are dropped and reported.

Run:  python scripts/build_watchlist.py
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CANDIDATES_PATH = HERE / "candidates.yaml"
WATCHLIST_PATH = HERE.parent / "watchlist.yaml"
FAILURES_PATH = HERE / "failures.yaml"

# Auto-drop a candidate after it fails verification this many consecutive runs.
DROP_AFTER_FAILURES = 3


def load_failures(path: Path = FAILURES_PATH) -> dict[str, int]:
    """Load the {isin: consecutive_failure_count} curation ledger."""
    if not path.exists():
        return {}
    return dict((yaml.safe_load(path.read_text(encoding="utf-8")) or {}).get("failures", {}))


def update_failures(existing: dict[str, int], resolved_isins: set[str],
                    unresolved_isins: set[str]) -> dict[str, int]:
    """Increment the fail count for unresolved candidates, reset it for resolved ones.

    A pure function (no I/O) so it is unit-testable: candidates that resolve this run drop
    out of the ledger; those that fail again have their streak incremented.
    """
    updated = {i: existing.get(i, 0) + 1 for i in unresolved_isins}
    # Resolved candidates clear their streak (removed from the ledger).
    for i in resolved_isins:
        updated.pop(i, None)
    return updated


def save_failures(failures: dict[str, int], path: Path = FAILURES_PATH) -> None:
    if failures:
        path.write_text(yaml.safe_dump({"failures": failures}, sort_keys=True),
                        encoding="utf-8")
    elif path.exists():
        path.unlink()

# Fields copied through to the verified watchlist (in this order).
OUTPUT_FIELDS = ["isin", "ticker", "name", "category", "asset_class",
                 "region", "domicile", "acc_dist", "ter"]


def load_candidates(path: Path = CANDIDATES_PATH) -> list[dict]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return raw.get("candidates", [])


def _has_data(df) -> bool:
    try:
        return df is not None and "Close" in df and df["Close"].dropna().shape[0] > 15
    except Exception:
        return False


def resolve(candidates: list[dict]) -> tuple[list[dict], list[dict]]:
    """Probe candidates round by round (one batched download per preference level).

    Returns (resolved, unresolved). Each resolved dict gains a single ``ticker``.
    """
    import yfinance as yf

    max_alts = max((len(c["tickers"]) for c in candidates), default=0)
    pending = list(candidates)
    resolved: list[dict] = []

    for level in range(max_alts):
        batch = {c["isin"]: c["tickers"][level] for c in pending if level < len(c["tickers"])}
        if not batch:
            break
        print(f"Probing round {level + 1}: {len(batch)} tickers …")
        data = yf.download(list(batch.values()), period="3mo", progress=False,
                           threads=True, auto_adjust=False, group_by="ticker")
        still_pending = []
        for c in pending:
            if level >= len(c["tickers"]):
                still_pending.append(c)
                continue
            t = c["tickers"][level]
            try:
                sub = data[t] if len(batch) > 1 else data
            except (KeyError, TypeError):
                sub = None
            if _has_data(sub):
                chosen = {k: v for k, v in c.items() if k != "tickers"}
                chosen["ticker"] = t
                chosen["domicile"] = c["isin"][:2]
                resolved.append(chosen)
            else:
                still_pending.append(c)
        pending = still_pending
        time.sleep(1.0)

    return resolved, pending


def write_watchlist(resolved: list[dict], path: Path = WATCHLIST_PATH) -> None:
    # De-duplicate by ISIN and order by category then name for a tidy file.
    seen: set[str] = set()
    final = []
    for c in sorted(resolved, key=lambda c: (c["category"], c["name"])):
        if c["isin"] in seen:
            continue
        seen.add(c["isin"])
        final.append({k: c[k] for k in OUTPUT_FIELDS if k in c})

    header = (
        "# UCITS ETF watchlist — AUTO-GENERATED by scripts/build_watchlist.py from\n"
        "# scripts/candidates.yaml. Each `ticker` was verified to return data on Yahoo\n"
        "# Finance. `isin` is the key; `ter` is seeded from issuer factsheets.\n\n"
    )
    path.write_text(header + yaml.safe_dump({"etfs": final}, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")


def main() -> int:
    candidates = load_candidates()
    failures = load_failures()
    # Config-driven curation: skip candidates that have failed verification repeatedly.
    demoted = {i for i, n in failures.items() if n >= DROP_AFTER_FAILURES}
    active = [c for c in candidates if c["isin"] not in demoted]
    print(f"Loaded {len(candidates)} candidates from {CANDIDATES_PATH.name}"
          f" ({len(demoted)} auto-dropped after ≥{DROP_AFTER_FAILURES} failures)\n")

    resolved, unresolved = resolve(active)
    write_watchlist(resolved)

    # Update the failure ledger (streak++ for still-failing, cleared for resolved).
    resolved_isins = {c["isin"] for c in resolved}
    unresolved_isins = {c["isin"] for c in unresolved}
    save_failures(update_failures(failures, resolved_isins, unresolved_isins))

    n_final = len(resolved_isins)
    print(f"\nResolved {n_final}/{len(candidates)} ETFs -> {WATCHLIST_PATH}")
    if unresolved:
        print("Could not resolve this run (failure streak incremented):")
        for c in unresolved:
            streak = failures.get(c["isin"], 0) + 1
            print(f"  - {c['name']} ({c['isin']}) tried {c['tickers']} [fails={streak}]")
    if demoted:
        print(f"Auto-dropped (≥{DROP_AFTER_FAILURES} consecutive failures): "
              + ", ".join(sorted(demoted)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
