"""Generate a verified watchlist.yaml from the candidate universe.

The candidate list lives in ``scripts/candidates.yaml`` (data, hand-maintained); this
module is the logic (probe + emit). For each candidate we try its Yahoo tickers
(different exchange listings of the same ISIN) and keep the first that returns price
history, batching the probes so we make only a few requests per round. Candidates whose
tickers all fail are dropped and reported.

Run:  python scripts/build_watchlist.py
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CANDIDATES_PATH = HERE / "candidates.yaml"
WATCHLIST_PATH = HERE.parent / "watchlist.yaml"

# Fields copied through to the verified watchlist (in this order).
OUTPUT_FIELDS = ["isin", "ticker", "name", "category", "asset_class",
                 "region", "domicile", "acc_dist", "ter"]


def load_candidates(path: Path = CANDIDATES_PATH) -> list[dict]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return raw.get("candidates", [])


def _has_data(df) -> bool:
    try:
        return df is not None and "Close" in df and df["Close"].dropna().shape[0] > 15
    except Exception:
        return False


def resolve(candidates: list[dict]) -> tuple[list[dict], list[dict]]:
    """Probe candidates round by round (one batched download per preference level).

    Returns (resolved, unresolved). Each resolved dict gains a single ``ticker``.
    """
    import yfinance as yf

    max_alts = max((len(c["tickers"]) for c in candidates), default=0)
    pending = list(candidates)
    resolved: list[dict] = []

    for level in range(max_alts):
        batch = {c["isin"]: c["tickers"][level] for c in pending if level < len(c["tickers"])}
        if not batch:
            break
        print(f"Probing round {level + 1}: {len(batch)} tickers …")
        data = yf.download(list(batch.values()), period="3mo", progress=False,
                           threads=True, auto_adjust=False, group_by="ticker")
        still_pending = []
        for c in pending:
            if level >= len(c["tickers"]):
                still_pending.append(c)
                continue
            t = c["tickers"][level]
            try:
                sub = data[t] if len(batch) > 1 else data
            except (KeyError, TypeError):
                sub = None
            if _has_data(sub):
                chosen = {k: v for k, v in c.items() if k != "tickers"}
                chosen["ticker"] = t
                chosen["domicile"] = c["isin"][:2]
                resolved.append(chosen)
            else:
                still_pending.append(c)
        pending = still_pending
        time.sleep(1.0)

    return resolved, pending


def write_watchlist(resolved: list[dict], path: Path = WATCHLIST_PATH) -> None:
    # De-duplicate by ISIN and order by category then name for a tidy file.
    seen: set[str] = set()
    final = []
    for c in sorted(resolved, key=lambda c: (c["category"], c["name"])):
        if c["isin"] in seen:
            continue
        seen.add(c["isin"])
        final.append({k: c[k] for k in OUTPUT_FIELDS if k in c})

    header = (
        "# UCITS ETF watchlist — AUTO-GENERATED by scripts/build_watchlist.py from\n"
        "# scripts/candidates.yaml. Each `ticker` was verified to return data on Yahoo\n"
        "# Finance. `isin` is the key; `ter` is seeded from issuer factsheets.\n\n"
    )
    path.write_text(header + yaml.safe_dump({"etfs": final}, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")


def main() -> int:
    candidates = load_candidates()
    print(f"Loaded {len(candidates)} candidates from {CANDIDATES_PATH.name}\n")
    resolved, unresolved = resolve(candidates)
    write_watchlist(resolved)

    n_final = len({c["isin"] for c in resolved})
    print(f"\nResolved {n_final}/{len(candidates)} ETFs -> {WATCHLIST_PATH}")
    if unresolved:
        print("Could not resolve (dropped):")
        for c in unresolved:
            print(f"  - {c['name']} ({c['isin']}) tried {c['tickers']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
